name: antimony

services:
  router:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

  frontend:
    container_name: frontend
    image: ghcr.io/antimony-team/antimony-interface:latest
    ports:
      - "8100:8100"

  backend:
    container_name: backend
    image: ghcr.io/antimony-team/antimony-backend:latest
    environment:
      - SB_NATIVE_USERNAME=admin
      - SB_NATIVE_PASSWORD=admin
    privileged: true
    command: -sqlite=true -config=./config.yml
    volumes:
      - ./config.yml:/app/config.yml
      - ./mnt/db:/app/db
      - ./mnt/storage:/app/storage/
      - ./mnt/run:/app/run/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"