site_name: Antimony Docs
site_author: Kian Gribi
site_url: https://antimony-team.github.io/
site_description: The documentation of the Antimonty platform. A visual approach to designing and managing Containerlab networks. 

repo_name: antimony-team/antimony-backend
repo_url: https://github.com/antimony-team/antimony-backend

nav:
 - Home: 'index.md'
 - Quick Start: 'quick-start.md'
 - User Manual: 'manual/index.md'
 - API Definition: 'api/index.md'
 - Issues: 'https://github.com/antimony-team/antimony-backend/issues/'

theme:
  name: material
  custom_dir: docs/overrides

  features:
    - navigation.top
    - navigation.tabs
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - toc.follow
    - content.tooltips
    - navigation.indexes
    - content.footnote.tooltips

  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    logo: logo
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  favicon: images/favicon-light.png

plugins:
  - offline

extra_css:
  - stylesheets/extra.css