site_name: Antimony Docs
site_author: Kian Gribi
site_url: https://antimony-team.github.io/
site_description: The documentation of the Antimonty platform. A visual approach to designing and managing Containerlab networks. 

repo_name: antimony-team/antimony
repo_url: https://github.com/antimony-team/antimony

nav:
  - Home: 'index.md'
  - Quick Start: 'quick-start.md'
  - User Manual:
    - Configuration: 'manual/configuration.md'
    - Glossary: 'manual/glossary.md'
    - Developer Guide: 'manual/development-setup.md'
  - Implementation:
    - 'implementation/index.md'
    - Authentication: 'implementation/authentication.md'
    - Topologies: 'implementation/topologies.md'
    - Lab Management: 'implementation/labs.md'
  - API Definition:
    - 'api/index.md'
    - Socket.IO Api: 'api/sockets.md'
    - Restful API:
      - 'api/restful.md'
  - Issues: 'https://github.com/antimony-team/antimony-backend/issues/'

theme:
  name: material
  custom_dir: docs/overrides

  features:
    - navigation.top
    - navigation.tabs
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - toc.follow
    - content.tooltips
    - navigation.indexes
    - content.footnote.tooltips

  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    logo: logo
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  favicon: images/favicon-light.png

plugins:
  - offline
  - swagger-ui-tag:
      tryItOutEnabled: false
      supportedSubmitMethods: []
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8
  - glightbox:
      width: 120%
      touchNavigation: true
      slide_effect: slide

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_css:
  - stylesheets/extra.css